-- reclassificar-sthefany-2026-10-02
-- gerado de antes.sqlite -> depois.sqlite
--   saidas_sem_faturamento: +3 ~0 -0
--   historico_reclassificacao: +8 ~0 -0
PRAGMA defer_foreign_keys = true;
INSERT INTO config (chave, valor) VALUES ('reclassificar-sthefany-2026-10-02', '"2026-10-02T13:53:25.317Z"');
INSERT INTO config (chave, valor) VALUES ('reclassificar-sthefany-2026-10-02:precondicao',
  CASE WHEN (SELECT COUNT(*) FROM "saidas_sem_faturamento") = 13
  AND (SELECT COUNT(*) FROM "historico_reclassificacao") = 31
  AND (SELECT COALESCE(SUM(qtd),0) FROM produtos) = 2244
  AND (SELECT COALESCE(MAX(id),0) FROM movimentos) = 3889
  AND (SELECT COALESCE(MAX(id),0) FROM vendas) = 22 THEN '"ok"' ELSE NULL END);
INSERT INTO "saidas_sem_faturamento" ("id", "tipo", "sentido", "data", "sku", "variacao", "variante_id", "qtd", "motivo", "observacao", "movimento_id", "estoque_refletido", "origem_usuario", "estornada", "estorno_em", "estorno_motivo", "estorno_movimento_id", "origem_registro", "historico_item_id", "inventario_id", "criado_em", "atualizado_em", "preco_unit", "preco_fonte", "custo_unit", "custo_fonte") VALUES (14, 'brinde', 'saida', '2025-12-24', '204997', NULL, NULL, 1, 'Presente vó Gustavo · Maleta', 'Planilha de vendas, Nº 797 — "cliente" Sthefany Marques. Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. texto da planilha "Presente vó Gustavo" identifica presente. Na planilha: Nº 797, R$ 169.00 marcado PAGO, antes contado como venda paga.', NULL, 0, NULL, 0, NULL, NULL, NULL, 'migracao_historico', 3514, NULL, '2026-10-02 13:52:51', NULL, 169, 'planilha', NULL, NULL);
INSERT INTO "saidas_sem_faturamento" ("id", "tipo", "sentido", "data", "sku", "variacao", "variante_id", "qtd", "motivo", "observacao", "movimento_id", "estoque_refletido", "origem_usuario", "estornada", "estorno_em", "estorno_motivo", "estorno_movimento_id", "origem_registro", "historico_item_id", "inventario_id", "criado_em", "atualizado_em", "preco_unit", "preco_fonte", "custo_unit", "custo_fonte") VALUES (15, 'brinde', 'saida', '2025-12-24', '377105', NULL, NULL, 1, 'Presente Geisa · Maleta', 'Planilha de vendas, Nº 798 — "cliente" Sthefany Marques. Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. texto da planilha "Presente Geisa" identifica presente. Na planilha: Nº 798, R$ 79.00 marcado PAGO, antes contado como venda paga.', NULL, 0, NULL, 0, NULL, NULL, NULL, 'migracao_historico', 3515, NULL, '2026-10-02 13:52:51', NULL, 79, 'planilha', NULL, NULL);
INSERT INTO "saidas_sem_faturamento" ("id", "tipo", "sentido", "data", "sku", "variacao", "variante_id", "qtd", "motivo", "observacao", "movimento_id", "estoque_refletido", "origem_usuario", "estornada", "estorno_em", "estorno_motivo", "estorno_movimento_id", "origem_registro", "historico_item_id", "inventario_id", "criado_em", "atualizado_em", "preco_unit", "preco_fonte", "custo_unit", "custo_fonte") VALUES (16, 'uso_proprio', 'saida', '2026-06-11', '322557', NULL, NULL, 1, 'Maleta', 'Planilha de vendas, Nº 1153 — "cliente" Sthefany Marques. Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 1153, R$ 129.00 marcado PAGO, antes contado como venda paga.', NULL, 0, NULL, 0, NULL, NULL, NULL, 'migracao_historico', 3870, NULL, '2026-10-02 13:52:51', NULL, 129, 'planilha', NULL, NULL);
INSERT INTO "historico_reclassificacao" ("id", "historico_item_id", "classe_nova", "confianca", "motivo", "saida_id", "status", "decidido_em", "decidido_por", "criado_em") VALUES (32, 2904, 'uso_proprio', 'alta', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 187, R$ 99.00 marcado PAGO, antes contado como venda paga.', NULL, 'aplicada', '2026-10-02 13:52:51', 'reclassificacao-sthefany-2026-10-02', '2026-10-02 13:52:51');
INSERT INTO "historico_reclassificacao" ("id", "historico_item_id", "classe_nova", "confianca", "motivo", "saida_id", "status", "decidido_em", "decidido_por", "criado_em") VALUES (33, 2914, 'uso_proprio', 'alta', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 197, R$ 129.00 marcado PAGO, antes contado como venda paga.', NULL, 'aplicada', '2026-10-02 13:52:51', 'reclassificacao-sthefany-2026-10-02', '2026-10-02 13:52:51');
INSERT INTO "historico_reclassificacao" ("id", "historico_item_id", "classe_nova", "confianca", "motivo", "saida_id", "status", "decidido_em", "decidido_por", "criado_em") VALUES (34, 2859, 'uso_proprio', 'alta', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 142, R$ 189.00 marcado PAGO, antes contado como venda paga.', NULL, 'aplicada', '2026-10-02 13:52:51', 'reclassificacao-sthefany-2026-10-02', '2026-10-02 13:52:51');
INSERT INTO "historico_reclassificacao" ("id", "historico_item_id", "classe_nova", "confianca", "motivo", "saida_id", "status", "decidido_em", "decidido_por", "criado_em") VALUES (35, 3514, 'brinde', 'alta', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. texto da planilha "Presente vó Gustavo" identifica presente. Na planilha: Nº 797, R$ 169.00 marcado PAGO, antes contado como venda paga.', 14, 'aplicada', '2026-10-02 13:52:51', 'reclassificacao-sthefany-2026-10-02', '2026-10-02 13:52:51');
INSERT INTO "historico_reclassificacao" ("id", "historico_item_id", "classe_nova", "confianca", "motivo", "saida_id", "status", "decidido_em", "decidido_por", "criado_em") VALUES (36, 3515, 'brinde', 'alta', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. texto da planilha "Presente Geisa" identifica presente. Na planilha: Nº 798, R$ 79.00 marcado PAGO, antes contado como venda paga.', 15, 'aplicada', '2026-10-02 13:52:51', 'reclassificacao-sthefany-2026-10-02', '2026-10-02 13:52:51');
INSERT INTO "historico_reclassificacao" ("id", "historico_item_id", "classe_nova", "confianca", "motivo", "saida_id", "status", "decidido_em", "decidido_por", "criado_em") VALUES (37, 3516, 'uso_proprio', 'alta', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 799, R$ 79.00 marcado PAGO, antes contado como venda paga.', NULL, 'aplicada', '2026-10-02 13:52:51', 'reclassificacao-sthefany-2026-10-02', '2026-10-02 13:52:51');
INSERT INTO "historico_reclassificacao" ("id", "historico_item_id", "classe_nova", "confianca", "motivo", "saida_id", "status", "decidido_em", "decidido_por", "criado_em") VALUES (38, 3793, 'brinde', 'alta', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. texto da planilha "Presente Cecilia" identifica presente. Na planilha: Nº 1076, R$ 49.00 marcado PAGO, antes contado como venda paga.', NULL, 'aplicada', '2026-10-02 13:52:51', 'reclassificacao-sthefany-2026-10-02', '2026-10-02 13:52:51');
INSERT INTO "historico_reclassificacao" ("id", "historico_item_id", "classe_nova", "confianca", "motivo", "saida_id", "status", "decidido_em", "decidido_por", "criado_em") VALUES (39, 3870, 'uso_proprio', 'alta', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 1153, R$ 129.00 marcado PAGO, antes contado como venda paga.', 16, 'aplicada', '2026-10-02 13:52:51', 'reclassificacao-sthefany-2026-10-02', '2026-10-02 13:52:51');
