-- reconciliacao:rodada-inventario-2026-10-02
-- gerado de base.sqlite -> depois.sqlite
--   inventarios: +0 ~0 -7
--   inventario_contagem: +0 ~0 -4
--   saidas_sem_faturamento: +0 ~15 -0
--   historico_reclassificacao: +0 ~37 -0
--   saidas_valor_historico: +12 ~0 -0
--   historico_reclassificacao_correcoes: +37 ~0 -0
PRAGMA defer_foreign_keys = true;
INSERT INTO config (chave, valor) VALUES ('reconciliacao:rodada-inventario-2026-10-02', '"2026-10-03T01:17:09.276Z"');
INSERT INTO config (chave, valor) VALUES ('reconciliacao:rodada-inventario-2026-10-02:precondicao',
  CASE WHEN (SELECT COUNT(*) FROM "inventarios") = 7
  AND (SELECT COUNT(*) FROM "inventario_contagem") = 4
  AND (SELECT COUNT(*) FROM "saidas_sem_faturamento") = 16
  AND (SELECT COUNT(*) FROM "historico_reclassificacao") = 39
  AND (SELECT COUNT(*) FROM "saidas_valor_historico") = 11
  AND (SELECT COUNT(*) FROM "historico_reclassificacao_correcoes") = 0
  AND (SELECT COALESCE(SUM(qtd),0) FROM produtos) = 2231
  AND (SELECT COALESCE(MAX(id),0) FROM movimentos) = 3901
  AND (SELECT COALESCE(MAX(id),0) FROM vendas) = 27 THEN '"ok"' ELSE NULL END);
UPDATE "saidas_sem_faturamento" SET "tipo" = 'brinde', "motivo" = 'Brinde Feira Franceschini - Dia das Mães', "observacao" = 'Planilha de vendas, Nº 351 — "cliente" Sthefany Marques. confirmado pela Sthefany: foi realmente um sorteio (DR-016/P17) (texto: "Sorteio (Feira Franceschini)") — Reconciliação das fontes operacionais de 26/09/2026 Classe corrigida de Sorteio para Brinde (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Sorteio (Feira Franceschini)".', "atualizado_em" = '2026-10-03 01:16:55', "custo_unit" = 11.73, "custo_fonte" = 'planilha' WHERE "id" = 1;
UPDATE "saidas_sem_faturamento" SET "tipo" = 'brinde', "motivo" = 'Presente Carmen', "observacao" = 'Planilha de vendas, Nº 842 — "cliente" Sthefany Marques. a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026 Classe corrigida de Uso próprio para Brinde (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Maleta".', "atualizado_em" = '2026-10-03 01:16:56', "custo_unit" = 14.52, "custo_fonte" = 'planilha' WHERE "id" = 2;
UPDATE "saidas_sem_faturamento" SET "motivo" = 'Presente Bruna', "observacao" = 'Planilha de vendas, Nº 1034 — "cliente" Sthefany Marques. a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Presente Bruna Maleta") — Reconciliação das fontes operacionais de 26/09/2026 Anotado (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Presente Bruna · Maleta".', "atualizado_em" = '2026-10-03 01:16:56', "custo_unit" = 17.3, "custo_fonte" = 'planilha' WHERE "id" = 3;
UPDATE "saidas_sem_faturamento" SET "motivo" = 'Presente Matheus Soares', "observacao" = 'Planilha de vendas, Nº 1037 — "cliente" Sthefany Marques. a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Presente Matheus Soares Maleta") — Reconciliação das fontes operacionais de 26/09/2026 Anotado (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Presente Matheus Soares · Maleta".', "atualizado_em" = '2026-10-03 01:16:56', "custo_unit" = 17.22, "custo_fonte" = 'planilha' WHERE "id" = 4;
UPDATE "saidas_sem_faturamento" SET "tipo" = 'brinde', "motivo" = 'Presente Emilly', "observacao" = 'Planilha de vendas, Nº 1172 — "cliente" Sthefany Marques. a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026 Classe corrigida de Uso próprio para Brinde (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Maleta".', "atualizado_em" = '2026-10-03 01:16:56', "custo_unit" = 7.66, "custo_fonte" = 'planilha' WHERE "id" = 5;
UPDATE "saidas_sem_faturamento" SET "tipo" = 'brinde', "motivo" = 'Presente Emilly', "observacao" = 'Planilha de vendas, Nº 1173 — "cliente" Sthefany Marques. a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026 Classe corrigida de Uso próprio para Brinde (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Maleta".', "atualizado_em" = '2026-10-03 01:16:56', "custo_unit" = 11, "custo_fonte" = 'planilha' WHERE "id" = 6;
UPDATE "saidas_sem_faturamento" SET "motivo" = 'Presente Jani Lopes', "observacao" = 'Planilha de vendas, Nº 1256 — "cliente" Sthefany Marques. a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Presente Jani Lopes Maleta") — Reconciliação das fontes operacionais de 26/09/2026 Anotado (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Presente Jani Lopes · Maleta".', "atualizado_em" = '2026-10-03 01:16:56', "custo_unit" = 14.52, "custo_fonte" = 'planilha' WHERE "id" = 7;
UPDATE "saidas_sem_faturamento" SET "observacao" = 'Planilha de vendas, Nº 1304 — "cliente" Inventário. a linha não registra dinheiro (valor zero ou lançada como ajuste) (texto: "PERDIDO") — Reconciliação das fontes operacionais de 26/09/2026 Anotado (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "PERDIDO".', "atualizado_em" = '2026-10-03 01:16:56' WHERE "id" = 8;
UPDATE "saidas_sem_faturamento" SET "observacao" = 'Planilha de vendas, Nº 1305 — "cliente" Inventário. diferença de inventário confirmada como perda pela Sthefany (DR-016/P17); a frase é observação (texto: "ACHO QUE FOI VENDIDO") — Reconciliação das fontes operacionais de 26/09/2026 Anotado (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "ACHO QUE FOI VENDIDO".', "atualizado_em" = '2026-10-03 01:16:56' WHERE "id" = 9;
UPDATE "saidas_sem_faturamento" SET "observacao" = 'Planilha de vendas, Nº 1306 — "cliente" Inventário. a linha não registra dinheiro (valor zero ou lançada como ajuste) (texto: "PERDIDO") — Reconciliação das fontes operacionais de 26/09/2026 Anotado (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "PERDIDO".', "atualizado_em" = '2026-10-03 01:16:56' WHERE "id" = 10;
UPDATE "saidas_sem_faturamento" SET "motivo" = 'Presente Mirele JS', "observacao" = 'Planilha de vendas, Nº 1343 — "cliente" Sthefany Marques. a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Presente Mirele JS Maleta") — Reconciliação das fontes operacionais de 26/09/2026 Anotado (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Presente Mirele JS · Maleta".', "atualizado_em" = '2026-10-03 01:16:56', "custo_unit" = 16.2, "custo_fonte" = 'planilha' WHERE "id" = 11;
UPDATE "saidas_sem_faturamento" SET "motivo" = 'Presente Luana JS', "observacao" = 'Planilha de vendas, Nº 1344 — "cliente" Sthefany Marques. a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Presente Luana JS Maleta") — Reconciliação das fontes operacionais de 26/09/2026 Anotado (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Presente Luana JS · Maleta".', "atualizado_em" = '2026-10-03 01:16:56', "custo_unit" = 22.43, "custo_fonte" = 'planilha' WHERE "id" = 12;
UPDATE "saidas_sem_faturamento" SET "motivo" = 'Presente vó Gustavo', "observacao" = 'Planilha de vendas, Nº 797 — "cliente" Sthefany Marques. Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. texto da planilha "Presente vó Gustavo" identifica presente. Na planilha: Nº 797, R$ 169.00 marcado PAGO, antes contado como venda paga. Anotado (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Presente vó Gustavo · Maleta".', "atualizado_em" = '2026-10-03 01:16:56', "custo_unit" = 49.01, "custo_fonte" = 'planilha' WHERE "id" = 14;
UPDATE "saidas_sem_faturamento" SET "motivo" = 'Presente Geisa', "observacao" = 'Planilha de vendas, Nº 798 — "cliente" Sthefany Marques. Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. texto da planilha "Presente Geisa" identifica presente. Na planilha: Nº 798, R$ 79.00 marcado PAGO, antes contado como venda paga. Anotado (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Presente Geisa · Maleta".', "atualizado_em" = '2026-10-03 01:16:56', "custo_unit" = 10.42, "custo_fonte" = 'planilha' WHERE "id" = 15;
UPDATE "saidas_sem_faturamento" SET "motivo" = 'Uso próprio', "observacao" = 'Planilha de vendas, Nº 1153 — "cliente" Sthefany Marques. Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 1153, R$ 129.00 marcado PAGO, antes contado como venda paga. Anotado (planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026). Rótulo anterior: "Maleta".', "atualizado_em" = '2026-10-03 01:16:55', "custo_unit" = 29.75, "custo_fonte" = 'planilha' WHERE "id" = 16;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Vó - Dia das Mães"' WHERE "id" = 1;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Mãe - Dia das Mães"' WHERE "id" = 2;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Brinde Feira Franceschini - Dia das Mães"' WHERE "id" = 3;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).' WHERE "id" = 4;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Ester"' WHERE "id" = 5;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Gustavo"' WHERE "id" = 6;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Gledson"' WHERE "id" = 7;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Taina"' WHERE "id" = 8;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).' WHERE "id" = 9;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).' WHERE "id" = 10;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).' WHERE "id" = 11;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).' WHERE "id" = 12;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Carmen"' WHERE "id" = 13;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Gisele"' WHERE "id" = 14;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Brinde Academia  Flynow"' WHERE "id" = 15;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Brinde Academia  Flynow"' WHERE "id" = 16;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Bruna"' WHERE "id" = 17;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Matheus Soares"' WHERE "id" = 18;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Emilly"' WHERE "id" = 20;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Emilly"' WHERE "id" = 21;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).' WHERE "id" = 22;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).' WHERE "id" = 23;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Jani Lopes"' WHERE "id" = 24;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "PERDIDO"' WHERE "id" = 25;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "ACHO QUE FOI VENDIDO"' WHERE "id" = 26;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "PERDIDO"' WHERE "id" = 27;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Brinde dia dos Pais"' WHERE "id" = 28;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Mirele JS"' WHERE "id" = 29;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Luana JS"' WHERE "id" = 30;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Não lembro o custo e nem para quem dei"' WHERE "id" = 32;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Vitória"' WHERE "id" = 33;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).' WHERE "id" = 34;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente vó Gustavo"' WHERE "id" = 35;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Geisa"' WHERE "id" = 36;
UPDATE "historico_reclassificacao" SET "classe_nova" = 'brinde', "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Angela"' WHERE "id" = 37;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Cecilia"' WHERE "id" = 38;
UPDATE "historico_reclassificacao" SET "motivo" = 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).' WHERE "id" = 39;
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (12, 16, 'custo_unit', NULL, 29.75, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:55');
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (13, 1, 'custo_unit', NULL, 11.73, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:55');
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (14, 14, 'custo_unit', NULL, 49.01, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:56');
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (15, 15, 'custo_unit', NULL, 10.42, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:56');
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (16, 2, 'custo_unit', NULL, 14.52, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:56');
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (17, 3, 'custo_unit', NULL, 17.3, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:56');
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (18, 4, 'custo_unit', NULL, 17.22, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:56');
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (19, 5, 'custo_unit', NULL, 7.66, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:56');
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (20, 6, 'custo_unit', NULL, 11, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:56');
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (21, 7, 'custo_unit', NULL, 14.52, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:56');
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (22, 11, 'custo_unit', NULL, 16.2, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:56');
INSERT INTO "saidas_valor_historico" ("id", "saida_id", "campo", "anterior", "novo", "fonte", "motivo", "em") VALUES (23, 12, 'custo_unit', NULL, 22.43, 'planilha', 'custo informado em planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (1, 34, 'uso_proprio', 'uso_proprio', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 142, R$ 189.00 marcado PAGO, antes contado como venda paga.', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).', NULL, 66.8, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (2, 4, 'uso_proprio', 'uso_proprio', 'a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "-") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).', NULL, 10.05, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (3, 9, 'uso_proprio', 'uso_proprio', 'a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).', NULL, 61.3, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (4, 10, 'uso_proprio', 'uso_proprio', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).', NULL, 10.14, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (5, 11, 'uso_proprio', 'uso_proprio', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).', NULL, 11.48, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (6, 12, 'uso_proprio', 'uso_proprio', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).', NULL, 14.61, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (7, 39, 'uso_proprio', 'uso_proprio', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 1153, R$ 129.00 marcado PAGO, antes contado como venda paga.', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).', NULL, 29.75, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 16, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (8, 22, 'uso_proprio', 'uso_proprio', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).', NULL, 76.5, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (9, 23, 'uso_proprio', 'uso_proprio', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática).', NULL, 40.86, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (10, 1, 'uso_proprio', 'brinde', 'a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "-") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Vó - Dia das Mães"', 'Presente Vó - Dia das Mães', 81, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (11, 2, 'uso_proprio', 'brinde', 'a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "-") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Mãe - Dia das Mães"', 'Presente Mãe - Dia das Mães', 73, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (12, 32, 'uso_proprio', 'brinde', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 187, R$ 99.00 marcado PAGO, antes contado como venda paga.', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Não lembro o custo e nem para quem dei"', 'Não lembro o custo e nem para quem dei', NULL, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (13, 33, 'uso_proprio', 'brinde', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 197, R$ 129.00 marcado PAGO, antes contado como venda paga.', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Vitória"', 'Presente Vitória', 46.62, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (14, 3, 'sorteio', 'brinde', 'confirmado pela Sthefany: foi realmente um sorteio (DR-016/P17) (texto: "Sorteio (Feira Franceschini)") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Brinde Feira Franceschini - Dia das Mães"', 'Brinde Feira Franceschini - Dia das Mães', 11.73, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 1, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (15, 5, 'uso_proprio', 'brinde', 'a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "-") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Ester"', 'Presente Ester', 2.56, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (16, 6, 'uso_proprio', 'brinde', 'a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "-") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Gustavo"', 'Presente Gustavo', 13.5, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (17, 7, 'uso_proprio', 'brinde', 'a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "-") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Gledson"', 'Presente Gledson', 45, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (18, 8, 'uso_proprio', 'brinde', 'a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Taina"', 'Presente Taina', 31.2, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:55');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (19, 35, 'brinde', 'brinde', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. texto da planilha "Presente vó Gustavo" identifica presente. Na planilha: Nº 797, R$ 169.00 marcado PAGO, antes contado como venda paga.', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente vó Gustavo"', 'Presente vó Gustavo', 49.01, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 14, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (20, 36, 'brinde', 'brinde', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. texto da planilha "Presente Geisa" identifica presente. Na planilha: Nº 798, R$ 79.00 marcado PAGO, antes contado como venda paga.', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Geisa"', 'Presente Geisa', 10.42, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 15, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (21, 37, 'uso_proprio', 'brinde', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. a planilha não diz o destino (só "Maleta"); a "cliente" é a própria Sthefany — uso próprio. Na planilha: Nº 799, R$ 79.00 marcado PAGO, antes contado como venda paga.', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Angela"', 'Presente Angela', 8.59, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (22, 13, 'uso_proprio', 'brinde', 'a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Carmen"', 'Presente Carmen', 14.52, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 2, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (23, 14, 'uso_proprio', 'brinde', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Gisele"', 'Presente Gisele', 18.22, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (24, 15, 'brinde', 'brinde', 'a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "Brinde Academia Flynow Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Brinde Academia  Flynow"', 'Brinde Academia  Flynow', 25.85, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (25, 16, 'brinde', 'brinde', 'a "cliente" é a própria Sthefany e não há pagamento registrado (texto: "Brinde Academia Flynow Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Brinde Academia  Flynow"', 'Brinde Academia  Flynow', 23.49, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (26, 17, 'brinde', 'brinde', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Presente Bruna Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Bruna"', 'Presente Bruna', 17.3, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 3, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (27, 18, 'brinde', 'brinde', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Presente Matheus Soares Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Matheus Soares"', 'Presente Matheus Soares', 17.22, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 4, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (28, 38, 'brinde', 'brinde', 'Confirmação humana do responsável em 02/10/2026: as linhas atribuídas a Sthefany Marques são uso próprio ou presentes dados por ela, não venda comercial. texto da planilha "Presente Cecilia" identifica presente. Na planilha: Nº 1076, R$ 49.00 marcado PAGO, antes contado como venda paga.', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Cecilia"', 'Presente Cecilia', 13.73, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (29, 20, 'uso_proprio', 'brinde', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Emilly"', 'Presente Emilly', 7.66, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 5, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (30, 21, 'uso_proprio', 'brinde', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Emilly"', 'Presente Emilly', 11, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 6, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (31, 24, 'brinde', 'brinde', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Presente Jani Lopes Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Jani Lopes"', 'Presente Jani Lopes', 14.52, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 7, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (32, 28, 'brinde', 'brinde', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Brinde dia dos Pais Maleta (Feira Franceschini)") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Brinde dia dos Pais"', 'Brinde dia dos Pais', 50.25, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', NULL, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (33, 29, 'brinde', 'brinde', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Presente Mirele JS Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Mirele JS"', 'Presente Mirele JS', 16.2, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 11, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (34, 30, 'brinde', 'brinde', 'a linha não registra dinheiro (valor zero ou lançada como zero) (texto: "Presente Luana JS Maleta") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "Presente Luana JS"', 'Presente Luana JS', 22.43, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 12, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (35, 25, 'perda', 'perda', 'a linha não registra dinheiro (valor zero ou lançada como ajuste) (texto: "PERDIDO") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "PERDIDO"', 'PERDIDO', NULL, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 8, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (36, 26, 'perda', 'perda', 'diferença de inventário confirmada como perda pela Sthefany (DR-016/P17); a frase é observação (texto: "ACHO QUE FOI VENDIDO") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "ACHO QUE FOI VENDIDO"', 'ACHO QUE FOI VENDIDO', NULL, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 9, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
INSERT INTO "historico_reclassificacao_correcoes" ("id", "reclassificacao_id", "classe_anterior", "classe_nova", "motivo_anterior", "motivo", "observacao", "custo_informado", "fonte", "saida_id", "decidido_por", "em") VALUES (37, 27, 'perda', 'perda', 'a linha não registra dinheiro (valor zero ou lançada como ajuste) (texto: "PERDIDO") — Reconciliação das fontes operacionais de 26/09/2026', 'Classificação dada pela Sthefany na planilha "Saiu sem faturar" (vence a classificação automática). — Observação da fonte: "PERDIDO"', 'PERDIDO', NULL, 'planilha "Saiu sem faturar.xlsx" da Sthefany, 02/10/2026', 10, 'planilha-saiu-sem-faturar-2026-10-02', '2026-10-03 01:16:56');
DELETE FROM "inventario_contagem" WHERE "inventario_id" = 6 AND "sku" = '127513' AND "variacao" = '';
DELETE FROM "inventario_contagem" WHERE "inventario_id" = 7 AND "sku" = '762279' AND "variacao" = '';
DELETE FROM "inventario_contagem" WHERE "inventario_id" = 7 AND "sku" = '917690' AND "variacao" = '';
DELETE FROM "inventario_contagem" WHERE "inventario_id" = 7 AND "sku" = '433595' AND "variacao" = '';
DELETE FROM "inventarios" WHERE "id" = 1;
DELETE FROM "inventarios" WHERE "id" = 2;
DELETE FROM "inventarios" WHERE "id" = 3;
DELETE FROM "inventarios" WHERE "id" = 4;
DELETE FROM "inventarios" WHERE "id" = 5;
DELETE FROM "inventarios" WHERE "id" = 6;
DELETE FROM "inventarios" WHERE "id" = 7;
